# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cPtHquAoXCQWS5cT77jadgGkUOnDwjg
"""

import joblib
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

data = fetch_california_housing()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target)

model = joblib.load("model.joblib")
preds = model.predict(X_test)
print("R^2 Score:", r2_score(y_test, preds))

