# -*- coding: utf-8 -*-
"""quantize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cPtHquAoXCQWS5cT77jadgGkUOnDwjg
"""

import joblib
import numpy as np

# Load model
model = joblib.load("model.joblib")

# Extract weights
params = {"coef_": model.coef_, "intercept_": model.intercept_}
joblib.dump(params, "unquant_params.joblib")

# Manual quantization (uint8)
scale = 255 / (np.max(params["coef_"]) - np.min(params["coef_"]))
quantized_coef = ((params["coef_"] - np.min(params["coef_"])) * scale).astype(np.uint8)
quantized_intercept = int((params["intercept_"] - np.min(params["coef_"])) * scale)

quant_params = {"coef_": quantized_coef, "intercept_": quantized_intercept}
joblib.dump(quant_params, "quant_params.joblib")

# Dequantization for inference
dequant_coef = quantized_coef.astype(np.float32) / scale + np.min(params["coef_"])
dequant_intercept = quantized_intercept / scale + np.min(params["coef_"])

# Manual inference
from sklearn.datasets import fetch_california_housing
X, y = fetch_california_housing(return_X_y=True)
y_pred = X.dot(dequant_coef) + dequant_intercept

from sklearn.metrics import r2_score
print("Quantized Model R2 Score:", r2_score(y, y_pred))

