name: CI Pipeline

on: [push]

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout docker_ci branch
      uses: actions/checkout@v3
      with:
          ref: docker_ci

    - name: List files before Docker build
      run: ls -la
    - name: Fetch train.py from dev branch
      run: |
          git fetch origin dev
          git checkout origin/dev -- train.py
    - name: Fetch quantize.py from quantization branch
      run: |
          git fetch origin dev
          git checkout origin/dev -- quantize.py
          
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train model
      run: |
        python train.py
    - name: Run Quantization
      run: |
        python quantize.py

    - name: Build Docker Image
      run: |
        docker build -t housing-model .

    - name: Run container to verify
      run: |
        docker run housing-model

