name: CI Pipeline

on: [push]

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train model
      run: |
        python CaliforniaHousingReg/train.py

    - name: Build Docker Image
      run: |
        docker build -t housing-model .

    - name: Run container to verify
      run: |
        docker run housing-model

    - name: DockerHub Login & Push
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.g24ai1022}}" --password-stdin
        docker tag housing-model g24ai1022/housing-model
        docker push g24ai1022/housing-model
